server:
  port: 8080

app:
  name: tale
  dev: false
  version: v1.0
  enableCdn: false
  max:
    file:
      size: 20480
  support_163_music: true
  support_gist: true


spring:
# 静态文件请求匹配方式
  mvc:
    view:
      static-path-pattern: /**
  jetbrick:
    template:
      charset: UTF-8

