server:
  port: 8080


app:
  name: tale
  dev: true
  version: v1.0
  enableCdn: false
  max:
    file:
      size: 20480
  support_163_music: true
  support_gist: true
mvc:
  view:
    404: /templates/comm/error_404.html
    500: /templates/comm/error_500.html
  statis: /upload


spring:
# 静态文件请求匹配方式
  mvc:
    view:
      static-path-pattern: /**

